### ISSUE TITLE
/users/me returns 500

### ISSUE THREAD

**Issue by sylvainlap** [tjwebb/sails-permissions#140]
Hi,

After being successfully logged in thanks to BasicAuth, a GET to /users/me (my API is pluralized) returns:

    error: Sending 500 ("Server Error") response: 
     TypeError: Cannot read property 'id' of undefined
        at /home/sylvainlap/DEV/WORKSPACE/ADaM/node_modules/sails-permissions/api/services/PermissionService.js:430:25
    From previous event:
        at /home/sylvainlap/DEV/WORKSPACE/ADaM/node_modules/sails-permissions/api/services/PermissionService.js:425:14
    From previous event:
        at Object.module.exports.isAllowedToPerformAction (/home/sylvainlap/DEV/WORKSPACE/ADaM/node_modules/sails-permissions/api/services/PermissionService.js:407:12)
        at Object.bound [as isAllowedToPerformAction] (/home/sylvainlap/DEV/WORKSPACE/ADaM/node_modules/sails/node_modules/lodash/dist/lodash.js:729:21)
        at /home/sylvainlap/DEV/WORKSPACE/ADaM/node_modules/sails-permissions/api/policies/RolePolicy.js:43:32
    From previous event:
        at module.exports (/home/sylvainlap/DEV/WORKSPACE/ADaM/node_modules/sails-permissions/api/policies/RolePolicy.js:41:6)
        at routeTargetFnWrapper (/home/sylvainlap/DEV/WORKSPACE/ADaM/node_modules/sails/lib/router/bind.js:179:5)
    at callbacks (/home/sylvainlap/DEV/WORKSPACE/ADaM/node_modules/sails/node_modules/express/lib/router/index.js:164:37)
    at param (/home/sylvainlap/DEV/WORKSPACE/ADaM/node_modules/sails/node_modules/express/lib/router/index.js:138:11)
    (...)

**Comment by ksylvan** [comment]
I'm getting the same, using the normal /auth/local API. 

Using POSTMAN to POST to /auth/local: { identifier: kayvan, password: test1234 }

    sails> info: user { owner: 3,
      email: 'kayvan.sylvan@disney.com',
      username: 'kayvan',
      createdAt: '2015-09-05T03:41:18.475Z',
      updatedAt: '2015-09-05T03:41:18.503Z',
      id: 3 } authenticated successfully

And now, GET to /user/me, and I see in the console:

    error: Sending 500 ("Server Error") response: 
     TypeError: Cannot read property 'id' of undefined
        at /usr/src/app/node_modules/sails-permissions/api/services/PermissionService.js:430:25
        at tryCatcher (/usr/local/lib/node_modules/sails/node_modules/waterline/node_modules/bluebird/js/main/util.js:26:23)
        at Promise._settlePromiseFromHandler (/usr/local/lib/node_modules/sails/node_modules/waterline/node_modules/bluebird/js/main/promise.js:503:31)
        at Promise._settlePromiseAt (/usr/local/lib/node_modules/sails/node_modules/waterline/node_modules/bluebird/js/main/promise.js:577:18)
        at Promise._settlePromises (/usr/local/lib/node_modules/sails/node_modules/waterline/node_modules/bluebird/js/main/promise.js:693:14)
        at Async._drainQueue (/usr/local/lib/node_modules/sails/node_modules/waterline/node_modules/bluebird/js/main/async.js:123:16)
        at Async._drainQueues (/usr/local/lib/node_modules/sails/node_modules/waterline/node_modules/bluebird/js/main/async.js:133:10)
        at Immediate.Async.drainQueues [as _onImmediate] (/usr/local/lib/node_modules/sails/node_modules/waterline/node_modules/bluebird/js/main/async.js:15:14)
        at processImmediate [as _immediateCallback] (timers.js:367:17) [TypeError: Cannot read property 'id' of undefined]

**Comment by ksylvan** [comment]
Putting in some logging and trying to figure out where this is coming from.

    >>> isAllowedToPerformAction action = read , model = undefined
    >>> isAllowedToPerformSingle model =  undefined
    error: Sending 500 ("Server Error") response: 
     TypeError: Cannot read property 'id' of undefined
        at /usr/src/app/node_modules/sails-permissions/api/services/PermissionService.js:433:25

**Comment by ksylvan** [comment]
I managed to avoid the problem by pinning my sails-permissions version to 1.4.2 (it had auto-updated to 1.4.3), so that would be the place to look for what changed.

So, with 1.4.2, /user/me is returning the user object of the authenticated user.

With 1.4.3, I am getting the behavior above.

**Comment by ryanwilliamquinn** [comment]
Thanks for the help debugging @ksylvan, it made my job much easier.

Fix is in this PR: https://github.com/tjwebb/sails-permissions/pull/152

**Comment by ksylvan** [comment]
Great. I verified the fix by "npm install --save https://github.com/sails-permissions" since the PR was merged into master.

So the next version of sails-permissions 1.4.x will have the fix in it.

**Comment by ryanwilliamquinn** [comment]
closed via 1.4.5
