### ISSUE TITLE
Error making requests: TypeError: Cannot read property 'initialize' of undefined

### ISSUE THREAD

**Issue by garrettboatman** [tjwebb/sails-permissions#144]
Followed the quickstart docs. Starting the server outputs:
```
debug: hookPath: /Users/garrettboatman/github/shows-api/node_modules/sails-auth/dist/api/hooks/auth
debug: marlinspike (auth): loading config from /Users/garrettboatman/github/shows-api/node_modules/sails-auth/dist/config
debug: hookPath: /Users/garrettboatman/github/shows-api/node_modules/sails-permissions/dist/api/hooks/permissions
debug: marlinspike (permissions): loading config from /Users/garrettboatman/github/shows-api/node_modules/sails-permissions/dist/config
debug: marlinspike (auth): loading Services from /Users/garrettboatman/github/shows-api/node_modules/sails-auth/dist/api/services...
debug: marlinspike (auth): loading Models...
debug: marlinspike (auth): loading Controllers...
debug: marlinspike (auth): loading Policies...
debug: marlinspike (permissions): loading Services from /Users/garrettboatman/github/shows-api/node_modules/sails-permissions/dist/api/services...
debug: marlinspike (permissions): loading Models...
debug: marlinspike (permissions): loading Controllers...
debug: marlinspike (permissions): loading Policies...
debug: sails-permissions: syncing waterline models

error: TypeError: Cannot set property '_modelCache' of undefined
    at /Users/garrettboatman/github/shows-api/node_modules/sails-permissions/dist/api/hooks/permissions/index.js:124:52 [TypeError: Cannot set property '_modelCache' of undefined]

```

The server still starts fine, but making any request outputs:
```
error: Sending 500 ("Server Error") response: 
 TypeError: Cannot read property 'initialize' of undefined
 at module.exports (/Users/garrettboatman/github/shows-api/node_modules/sails-auth/dist/api/policies/passport.js:35:11)
    at routeTargetFnWrapper (/Users/garrettboatman/github/shows-api/node_modules/sails/lib/router/bind.js:179:5)
    at callbacks (/Users/garrettboatman/github/shows-api/node_modules/sails/node_modules/express/lib/router/index.js:164:37)
    at param (/Users/garrettboatman/github/shows-api/node_modules/sails/node_modules/express/lib/router/index.js:138:11)
    at pass (/Users/garrettboatman/github/shows-api/node_modules/sails/node_modules/express/lib/router/index.js:145:5)
    at nextRoute (/Users/garrettboatman/github/shows-api/node_modules/sails/node_modules/express/lib/router/index.js:100:7)
    at callbacks (/Users/garrettboatman/github/shows-api/node_modules/sails/node_modules/express/lib/router/index.js:167:11)
    at /Users/garrettboatman/github/shows-api/node_modules/sails/lib/router/bind.js:187:7
    at module.exports (/Users/garrettboatman/github/shows-api/node_modules/sails-auth/dist/api/policies/basicAuth.js:13:12)
    at routeTargetFnWrapper (/Users/garrettboatman/github/shows-api/node_modules/sails/lib/router/bind.js:179:5)
    at callbacks (/Users/garrettboatman/github/shows-api/node_modules/sails/node_modules/express/lib/router/index.js:164:37)
    at param (/Users/garrettboatman/github/shows-api/node_modules/sails/node_modules/express/lib/router/index.js:138:11)
    at pass (/Users/garrettboatman/github/shows-api/node_modules/sails/node_modules/express/lib/router/index.js:145:5)
    at nextRoute (/Users/garrettboatman/github/shows-api/node_modules/sails/node_modules/express/lib/router/index.js:100:7)
    at callbacks (/Users/garrettboatman/github/shows-api/node_modules/sails/node_modules/express/lib/router/index.js:167:11)
    at /Users/garrettboatman/github/shows-api/node_modules/sails/lib/router/bind.js:187:7
    at clearHeaders (/Users/garrettboatman/github/shows-api/node_modules/sails/lib/hooks/cors/index.js:209:3)
    at routeTargetFnWrapper (/Users/garrettboatman/github/shows-api/node_modules/sails/lib/router/bind.js:179:5)
    at callbacks (/Users/garrettboatman/github/shows-api/node_modules/sails/node_modules/express/lib/router/index.js:164:37)
    at param (/Users/garrettboatman/github/shows-api/node_modules/sails/node_modules/express/lib/router/index.js:138:11)
    at pass (/Users/garrettboatman/github/shows-api/node_modules/sails/node_modules/express/lib/router/index.js:145:5)
    at nextRoute (/Users/garrettboatman/github/shows-api/node_modules/sails/node_modules/express/lib/router/index.js:100:7) [TypeError: Cannot read property 'initialize' of undefined]

```

Any ideas?

**Comment by KashmirTheOne** [comment]
I have the same problem with
<code>error: TypeError: Cannot set property '_modelCache' of undefined</code>
Even in a clean project

Notes:
I'm in Sails 0.11

**Comment by ryanwilliamquinn** [comment]
Which versions of sails-permissions and sails auth are installed?

**Comment by tschneid** [comment]
Same problem here.
```
node_modules/sails-permissions/dist/api/hooks/permissions/index.js:124:52 [TypeError: Cannot set property '_modelCache' of undefined]
```
sails 0.11.2
sails-permissions 2.1.3
sails-auth 2.1.1

**Comment by tschneid** [comment]
It's working in sails 0.12.0-rc3.
In sails 0.11 the hook seems to be called 'sails-permissions' (not just 'permissions').

**Comment by chipsenkbeil** [comment]
sails 0.12.0-rc3
sails-permissions 2.1.3
sails-auth 2.1.1

Still fails with `TypeError: Cannot set property '_modelCache' of undefined'.

**Comment by tjwebb** [comment]
Can you try sails-permissions `master`?

**Comment by Grumos** [comment]
sails 0.12.0-rc3
sails-permissions 2.1.11 -> master ?
sails-auth 2.1.1

Still fails with `TypeError: Cannot set property '_modelCache' of undefined'.

**Comment by patrickdebruijn** [comment]
same here: error: TypeError: Cannot set property '_modelCache' of undefined

sails 0.12.0-rc3
sails-permissions 2.1.11
sails-auth 2.1.1

**Comment by khchan** [comment]
I am able to get my project to work if I go into node_modules/sails-permissions and modify wherever the hook is used from `sails.hooks.permissions` to `sails.hooks['sails-permissions']`.

**Comment by PaulWoodIII** [comment]
+1 getting this error as well and wish there was a clear answer

**Comment by khchan** [comment]
I updated my previous comment in this thread with a solution that finally worked for me, @PaulWoodIII did creating a `config/installedHooks.js` file work for you?

**Comment by PaulWoodIII** [comment]
no it did not, anything else beyond just the file that I should also do I'm new to sails so handholding would be appreciated

**Comment by dioptre** [comment]
+1 that fix worked for me

**Comment by yadavji83** [comment]
@khchan ur solution removed the error: TypeError: Cannot set property '_modelCache' of undefined

but now this error is coming: error: TypeError: Cannot set property 'protocols' of undefined

**Comment by yadavji83** [comment]
Just to give more insight of the issue. My sails app was working fine with sails0.12.0-rc3, sails-auth2.1.1 and sails-permissions2.1.11

But i ran npm install which added latest release of sails0.12.0-rc4 and the issue started to come after that. I uninstalled sails and then reinstalled version 0.12.0-rc3 but this error is still there.

**Comment by PaulWoodIII** [comment]
Still having trouble, and i'm now to where @yadavji83 is having trouble, Heres my console output:

    info: sails-permissions: admin user does not exist; creating...
    error: TypeError: Cannot read property 'protocols' of undefined
      at module.exports.register (/home/ubuntu/workspace/node_modules/sails-auth/api/models/User.js:49:30)
      at bound.module.exports.register (/home/ubuntu/workspace/node_modules/sails-auth/api/models/User.js:48:12)
      at bound [as register] (/home/ubuntu/workspace/node_modules/sails/node_modules/lodash/dist/lodash.js:729:21)
      at /home/ubuntu/workspace/node_modules/sails-permissions/dist/config/fixtures/user.js:27:30
    From previous event:
      at processImmediate [as _immediateCallback] (timers.js:368:17)
    From previous event:
      at [object Object].Deferred.then (/home/ubuntu/workspace/node_modules/sails/node_modules/waterline/lib/waterline/query/deferred.js:497:27)
      at Object.exports.create (/home/ubuntu/workspace/node_modules/sails-permissions/dist/config/fixtures/user.js:23:90)
      at /home/ubuntu/workspace/node_modules/sails-permissions/dist/api/hooks/permissions/index.js:130:73 [TypeError: Cannot read property 'protocols' of undefined]

So I get that MerlinSpike is injecting the User.js Model code into my app, however it looks like it depends on passport. This is `sails-auth/api/models/User.js:44-55`

      /**
       * Register a new User with a passport
       */
      register: function (user) {
        return new Promise(function (resolve, reject) {
          sails.services.passport.protocols.local.createUser(user, function (error, created) {
            if (error) return reject(error);
            
            resolve(created);
          });
        });
      }
Can someone confirm the dependency on passport and passport-local.

**Comment by chirag200666** [comment]
Upgrading sails to 0.12.0-rc7 fixed the issue for me.
{
...
"sails": "^0.12.0-rc7",
"sails-auth": "~2.1.1",
"sails-permissions": "~2.1.11"
...
}

**Comment by PaulWoodIII** [comment]
@chirag200666 yes thanks for your update I've managed to get things working now and I wouldn't have come back to this package if you hadn't updated your status
