### ISSUE TITLE
An error when run 'sails www --prod'

### ISSUE THREAD

**Issue by imfly** [tjwebb/sails-permissions#158]
Hi, 
I find an error when I execute `sails www --prod`

The logs:

```
kuby@debian:~/$ sails www --prod
/path/to/project/node_modules/sails-permissions/node_modules/sails-auth/api/services/passport.js:281
  var strategies = sails.config.passport;
                   ^
ReferenceError: sails is not defined
    at Authenticator.passport.loadStrategies (/path/to/project/node_modules/sails-permissions/node_modules/sails-auth/api/services/passport.js:281:20)
    at Authenticator.bound [as loadStrategies] (~/.npm/lib/node_modules/sails/node_modules/lodash/dist/lodash.js:729:21)
    at Hook.initialize (/path/to/project/node_modules/sails-auth/api/hooks/sails-auth.js:4:31)
    at Hook.bound [as initialize] (~/.npm/lib/node_modules/sails/node_modules/lodash/dist/lodash.js:729:21)
    at /home/kuby/.npm/lib/node_modules/sails/lib/hooks/index.js:75:14
    at /home/kuby/.npm/lib/node_modules/sails/node_modules/async/lib/async.js:451:17
    at /home/kuby/.npm/lib/node_modules/sails/node_modules/async/lib/async.js:441:17
    at _each (~/.npm/lib/node_modules/sails/node_modules/async/lib/async.js:46:13)
    at Immediate.taskComplete (~/.npm/lib/node_modules/sails/node_modules/async/lib/async.js:440:13)
    at processImmediate [as _immediateCallback] (timers.js:367:17)
```

Can anyone know how to resolve this?

Thx

**Comment by imfly** [comment]
I think if the `sails`  exists only when the application is running.

**Comment by ryanwilliamquinn** [comment]
does it work if you run `sails lift`?
