### ISSUE TITLE
Error: Cannot find module 'lodash' for fresh installation

### ISSUE THREAD

**Issue by dbkaplun** [tjwebb/sails-permissions#191]
```
$ sails lift

info: Starting app...

module.js:339
    throw err;
    ^

Error: Cannot find module 'lodash'
    at Function.Module._resolveFilename (module.js:337:15)
    at Function.Module._load (module.js:287:25)
    at Module.require (module.js:366:17)
    at require (module.js:385:17)
    at Object.<anonymous> (/Users/dan/stuff/dbkaplun-app-boilerplate/config/passport.js:3:9)
    at Module._compile (module.js:435:26)
    at Object.Module._extensions..js (module.js:442:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:311:12)
    at Module.require (module.js:366:17)
    at require (module.js:385:17)
    at /Users/dan/stuff/dbkaplun-app-boilerplate/node_modules/include-all/index.js:129:29
    at Array.forEach (native)
    at requireAll (/Users/dan/stuff/dbkaplun-app-boilerplate/node_modules/include-all/index.js:44:9)
    at buildDictionary (/Users/dan/stuff/dbkaplun-app-boilerplate/node_modules/sails/node_modules/sails-build-dictionary/index.js:68:14)
    at Function.module.exports.aggregate (/Users/dan/stuff/dbkaplun-app-boilerplate/node_modules/sails/node_modules/sails-build-dictionary/index.js:190:9)
```

**Comment by dbkaplun** [comment]
After installing, we're missing a `sails-permissions/config/passport` file:
```
$ npm install --save lodash
lodash@3.10.1 node_modules/lodash

 23:35:25  dan@elise:~/stuff/dbkaplun-app-boilerplate   master ✘ ⬇ ⬆ ✹ 
$ sails lift

info: Starting app...

module.js:339
    throw err;
    ^

Error: Cannot find module 'sails-permissions/config/passport'
    at Function.Module._resolveFilename (module.js:337:15)
    at Function.Module._load (module.js:287:25)
    at Module.require (module.js:366:17)
    at require (module.js:385:17)
    at Object.<anonymous> (/Users/dan/stuff/dbkaplun-app-boilerplate/config/passport.js:4:14)
    at Module._compile (module.js:435:26)
    at Object.Module._extensions..js (module.js:442:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:311:12)
    at Module.require (module.js:366:17)
    at require (module.js:385:17)
    at /Users/dan/stuff/dbkaplun-app-boilerplate/node_modules/include-all/index.js:129:29
    at Array.forEach (native)
    at requireAll (/Users/dan/stuff/dbkaplun-app-boilerplate/node_modules/include-all/index.js:44:9)
    at buildDictionary (/Users/dan/stuff/dbkaplun-app-boilerplate/node_modules/sails/node_modules/sails-build-dictionary/index.js:68:14)
    at Function.module.exports.aggregate (/Users/dan/stuff/dbkaplun-app-boilerplate/node_modules/sails/node_modules/sails-build-dictionary/index.js:190:9)
```

**Comment by WirelessElephant** [comment]
I also had this problem on a fresh install. I did not have the `sails-permissions/config/passport` missing module. I fixed the lodash problem by `npm install lodash`.
