### ISSUE TITLE
NPM 3.x Error: Cannot find module 'C:\path\to\sails-permissions\generator'

### ISSUE THREAD

**Issue by snlacks** [tjwebb/sails-permissions#222]
My fix was to change .sailsrc to: 

 ```
{
  "generators": {
    "modules": {
      "permissions-api": "**node_modules**/sails-permissions/generator"
    }
  }
}
```

**Comment by Download** [comment]
I had the same issue:

```sh
c:\ws\sails-project>sails generate permissions-api
error: Error in "permissions-api" generator (loaded from sails-permissions/generator)
C:\Users\...\AppData\Roaming\npm\node_modules\sails\node_modules\sails-generate\lib\index.js:51
      throw e;
      ^

Error: Cannot find module 'c:\ws\sails-project\sails-permissions\generator'
    at Function.Module._resolveFilename (module.js:326:15)
    at Function.Module._load (module.js:277:25)
    at Module.require (module.js:354:17)
    at require (internal/module.js:12:17)
    at module.exports (C:\Users\...\AppData\Roaming\npm\node_modules\sails\node_modules\sails-generate\lib\index.js:71:19)
    at Command.module.exports (C:\Users\...\AppData\Roaming\npm\node_modules\sails\bin\sails-generate.js:107:10)
    at Command.listener (C:\Users\...\AppData\Roaming\npm\node_modules\sails\node_modules\commander\index.js:301:8)
    at emitTwo (events.js:87:13)
    at Command.emit (events.js:172:7)
    at Command.parseArgs (C:\Users\...\AppData\Roaming\npm\node_modules\sails\node_modules\commander\index.js:615:12)
```

After performing your suggested fix:

```sh
c:\ws\sails-project>sails generate permissions-api
info: Created a new permissions-api ("permissions-api")!
```

So thank you!

**Comment by KingOfBeasts** [comment]
I had the same issue,so thank you!
