### ISSUE TITLE
PermissionService Error

### ISSUE THREAD

**Issue by GregSithole** [tjwebb/sails-permissions#250]
Hi

I'm getting an error when I try to create a user.
So I'm able to login which returns my user details.

And then when I try to create a random user, I get a 
`PermissionService.findModelPermissions is not a function`.

My full error is as followed: 
` TypeError: PermissionService.findModelPermissions is not a function
    at module.exports (C:\Users\Mystere\auth-permission\node_modules\sails-permissions\dist\api\policies\PermissionPolicy.js:34:21)
    at routeTargetFnWrapper (C:\Users\Mystere\AppData\Roaming\npm\node_modules\sails\lib\router\bind.js:181:5)
    at callbacks (C:\Users\Mystere\AppData\Roaming\npm\node_modules\sails\node_modules\@sailshq\express\lib\router\index.js:164:37)
    at param (C:\Users\Mystere\AppData\Roaming\npm\node_modules\sails\node_modules\@sailshq\express\lib\router\index.js:138:11)
    at param (C:\Users\Mystere\AppData\Roaming\npm\node_modules\sails\node_modules\@sailshq\express\lib\router\index.js:135:11)
    at pass (C:\Users\Mystere\AppData\Roaming\npm\node_modules\sails\node_modules\@sailshq\express\lib\router\index.js:145:5)
    at nextRoute (C:\Users\Mystere\AppData\Roaming\npm\node_modules\sails\node_modules\@sailshq\express\lib\router\index.js:100:7)
    at callbacks (C:\Users\Mystere\AppData\Roaming\npm\node_modules\sails\node_modules\@sailshq\express\lib\router\index.js:167:11)
    at OwnerPolicy (C:\Users\Mystere\auth-permission\node_modules\sails-permissions\dist\api\policies\OwnerPolicy.js:33:3)
    at routeTargetFnWrapper (C:\Users\Mystere\AppData\Roaming\npm\node_modules\sails\lib\router\bind.js:181:5)
    at callbacks (C:\Users\Mystere\AppData\Roaming\npm\node_modules\sails\node_modules\@sailshq\express\lib\router\index.js:164:37)
    at param (C:\Users\Mystere\AppData\Roaming\npm\node_modules\sails\node_modules\@sailshq\express\lib\router\index.js:138:11)
    at param (C:\Users\Mystere\AppData\Roaming\npm\node_modules\sails\node_modules\@sailshq\express\lib\router\index.js:135:11)
    at pass (C:\Users\Mystere\AppData\Roaming\npm\node_modules\sails\node_modules\@sailshq\express\lib\router\index.js:145:5)
    at nextRoute (C:\Users\Mystere\AppData\Roaming\npm\node_modules\sails\node_modules\@sailshq\express\lib\router\index.js:100:7)
    at callbacks (C:\Users\Mystere\AppData\Roaming\npm\node_modules\sails\node_modules\@sailshq\express\lib\router\index.js:167:11)
    at module.exports (C:\Users\Mystere\auth-permission\node_modules\sails-permissions\dist\api\policies\AuditPolicy.js:22:3)
    at routeTargetFnWrapper (C:\Users\Mystere\AppData\Roaming\npm\node_modules\sails\lib\router\bind.js:181:5)
    at callbacks (C:\Users\Mystere\AppData\Roaming\npm\node_modules\sails\node_modules\@sailshq\express\lib\router\index.js:164:37)
    at param (C:\Users\Mystere\AppData\Roaming\npm\node_modules\sails\node_modules\@sailshq\express\lib\router\index.js:138:11)
    at param (C:\Users\Mystere\AppData\Roaming\npm\node_modules\sails\node_modules\@sailshq\express\lib\router\index.js:135:11)
    at pass (C:\Users\Mystere\AppData\Roaming\npm\node_modules\sails\node_modules\@sailshq\express\lib\router\index.js:145:5)`

**Comment by GregSithole** [comment]
Never mind, I wasn't using the PermissionService...
