### ISSUE TITLE
Server crashes on POST /user if username or email exists.

### ISSUE THREAD

**Issue by cratervale** [tjwebb/sails-permissions#34]
An error response would be preferable to a server crash.  Here is the full stack trace:

```
debug: Error (E_VALIDATION) :: 2 attributes are invalid
: 
  at WLValidationError.WLError (/[User]/.node/lib/node_modules/sails/node_modules/waterline/lib/waterline/error/WLError.js:33:18)
  at new WLValidationError (/[User]/.node/lib/node_modules/sails/node_modules/waterline/lib/waterline/error/WLValidationError.js:20:28)
  at duckType (/[User]/.node/lib/node_modules/sails/node_modules/waterline/lib/waterline/error/index.js:60:12)
  at errorify (/[User]/.node/lib/node_modules/sails/node_modules/waterline/lib/waterline/error/index.js:39:10)
  at wrappedCallback (/[User]/.node/lib/node_modules/sails/node_modules/waterline/lib/waterline/utils/normalize.js:320:15)
  at _normalizeCallback.callback.error (/[User]/.node/lib/node_modules/sails/node_modules/waterline/node_modules/switchback/lib/normalize.js:42:31)
  at _switch (/[User]/.node/lib/node_modules/sails/node_modules/waterline/node_modules/switchback/lib/factory.js:46:28)
  at [object Object]._onTimeout (/[Project]/node_modules/sails-disk/lib/adapter.js:179:10)
  at Timer.listOnTimeout [as ontimeout] (timers.js:110:15)


Invalid attributes sent to undefined:
 • username
   • A record with that `username` already exists (`cratervale`).
 • email
   • A record with that `email` already exists (`cratervale@example.com`).

verbose: Lowering sails...
verbose: Sent kill signal to child process (21472)...
verbose: Shutting down HTTP server...

/[Project]/node_modules/sails-auth/api/services/protocols/local.js:42
          throw new Error('Error.Passport.Email.Exists');
                ^
Error: Error.Passport.Email.Exists
  at /[Project]/node_modules/sails-auth/api/services/protocols/local.js:42:17
  at /[User]/.node/lib/node_modules/sails/node_modules/waterline/lib/waterline/query/dql/create.js:216:14
  at bound (/[User]/.node/lib/node_modules/sails/node_modules/lodash/dist/lodash.js:957:21)
  at applyInOriginalCtx (/[User]/.node/lib/node_modules/sails/node_modules/waterline/lib/waterline/utils/normalize.js:416:80)
  at wrappedCallback (/[User]/.node/lib/node_modules/sails/node_modules/waterline/lib/waterline/utils/normalize.js:326:16)
  at _normalizeCallback.callback.error (/[User]/.node/lib/node_modules/sails/node_modules/waterline/node_modules/switchback/lib/normalize.js:42:31)
  at _switch (/[User]/.node/lib/node_modules/sails/node_modules/waterline/node_modules/switchback/lib/factory.js:46:28)
  at afterwards 
```

**Comment by bgulotta** [comment]
Pretty sure I have fixed and tested this issue in sails-auth. My PR is waiting to be accepted and merged.

**Comment by cratervale** [comment]
Awesome, loving these projects :dancers:

**Comment by bgulotta** [comment]
Yep. Me too!!!
