### ISSUE TITLE
Cannot set property '*' of undefined

### ISSUE THREAD

**Issue by willemmulder** [tjwebb/sails-permissions#41]
I've created a brand new Sails app, then added 'sails-permissions' to the package.json as a dependency, then added the generator to the .sailsrc and ran 'sails generate permissions-api'. All well so far. Then when I try to lift, I get

```
appFolder\node_modules\sails-permissions\api\hooks\sails-permissions.js:107

    policies.AuthController['*'] = true
                                 ^
TypeError: Cannot set property '*' of undefined
    at validatePolicyConfig (appFolder\node_modules\sails-permissions\api\hooks\sails-permissions.js:107:34)
    at Hook.initialize (appFolder\node_modules\sails-permissions\api\hooks\sails-permissions.js:23:12)
    at Hook.bound [as initialize] (appFolder\node_modules\sails\node_modules\lodash\dist\lodash.js:729:21)
    at appFolder\node_modules\sails\lib\hooks\index.js:75:14 at appFolder\node_modules\sails\node_modules\async\lib\async.js:454:17
    at appFolder\node_modules\sails\node_modules\async\lib\async.js:444:17
    at Array.forEach (native)
    at _each (appFolder\node_modules\sails\node_modules\async\lib\async.js:
46:24)
    at Object.taskComplete (appFolder\node_modules\sails\node_modules\async\lib\async.js:443:13)
    at processImmediate [as _immediateCallback] (timers.js:330:15)
```

Any clues?

**Comment by tjwebb** [comment]
Did you set up the policies as described in the README?

**Comment by willemmulder** [comment]
That was the problem indeed! 
I didn't think it would matter how/whether I would use the policies so I ignored that part.
Sorry for the confusion.

Thanks!
