### ISSUE TITLE
Sails 0.11 : The hook `sails-permissions` is taking too long to load.

### ISSUE THREAD

**Issue by anthonybriand** [tjwebb/sails-permissions#48]
Hello,

After I have installed sails-permissions and configured it, I can't lift, sails gave me an error : 

There is the log : 
> info: Starting app...
debug: sails-permissions: syncing waterline models
debug: sails-permissions: admin user does not exist; creating...
debug: User.afterCreate.setOwner { '@type': 'd',
  '@class': 'user',
  username: 'acidspike',
  email: 'xxxxxxx@gmail.com',
  createdBy: null,
  owner: null,
  createdAt: Thu Apr 30 2015 12:49:34 GMT+0200 (CEST),
  updatedAt: Thu Apr 30 2015 12:49:34 GMT+0200 (CEST),
  id: '#17:0' }
error: Error: The hook `sails-permissions` is taking too long to load.
Make sure it is triggering its `initialize()` callback, or else set `sails.config.sails-permissions._hookTimeout to a higher value (currently 20000)
    at tooLong [as _onTimeout] (/usr/local/lib/node_modules/sails/lib/app/private/loadHooks.js:92:21)
    at Timer.listOnTimeout (timers.js:110:15)

I am working on Sails 0.11, sails-orientdb adapter 0.10.50 and sails-permissions 1.0.16

I have sought and the problem seems to be in api/models/User.js line 36, at the user update it never goes to the next step.

In my database the user record is updated 6919 times (depending on computer speed).

**Comment by anthonybriand** [comment]
Sorry it seems to be related with a save problem in sails-orientdb see here : https://github.com/appscot/sails-orientdb/issues/89
