### ISSUE TITLE
TypeError: undefined is not a function (Promise.map)

### ISSUE THREAD

**Issue by chrisfrancis27** [tjwebb/sails-permissions#51]
Bashing my head a bit trying to figure this one out. I can't lift my Sails app. However, when I create a brand new test app and follow the same steps (generate a couple of model/controllers and install sails-permissions) it works just fine. Here's the full stacktrace (paths shortened for brevity):

    error: TypeError: undefined is not a function
    at Object.exports.createModels (.../server/node_modules/sails-permissions/config/fixtures/model.js:18:18)
    at initializeFixtures (.../server/node_modules/sails-permissions/api/hooks/sails-permissions.js:52:49)
    at .../server/node_modules/sails-permissions/api/hooks/sails-permissions.js:36:13
    at tryCatcher (.../server/node_modules/bluebird/js/main/util.js:24:31)
    at Promise._settlePromiseFromHandler (.../server/node_modules/bluebird/js/main/promise.js:454:31)
    at Promise._settlePromiseAt (.../server/node_modules/bluebird/js/main/promise.js:530:18)
    at Promise._settlePromises (.../server/node_modules/bluebird/js/main/promise.js:646:14)
    at Async._drainQueue (.../server/node_modules/bluebird/js/main/async.js:177:16)
    at Async._drainQueues (.../server/node_modules/bluebird/js/main/async.js:187:10)
    at Immediate.Async.drainQueues [as _onImmediate] (.../server/node_modules/bluebird/js/main/async.js:15:14)
    at processImmediate [as _immediateCallback] (timers.js:358:17) [TypeError: undefined is not a function]

It seems like it's somehow falling back to the default Promises/A+ implementation in Node, as opposed to the more full-featured [Bluebird API](https://github.com/petkaantonov/bluebird/blob/master/API.md#mapfunction-mapper--object-options---promise). Here's my version output:

    node --version
    └── v0.12.0
    sails --version
    └── 0.11.0
    npm --version
    └── 2.7.1
    npm ls bluebird 
    └── bluebird@2.9.25

It all works if I add the following lines to the top of `sails-permissions/config/fixtures/model.js`:

    /* global -Promise */
    var Promise = require('bluebird');

However, I'm unsure about submitting a PR for this as I really don't understand the ins and outs of it. Is it safe to assume explicitly requiring the Bluebird Promise implementation is a Good Thing™? Why would this be throwing an error in one project, but not another? I'm `require`-ing Bluebird in my own custom adapter, but if I remove that adapter and remove Bluebird from my `package.json` it still throws the same error. Any help would be appreciated!

**Comment by tjwebb** [comment]
Hey @chrisfrancis27 thanks for the report. Would you mind submitting a PR? If I omitted that require, that's an error on my part.

**Comment by nathanmarks** [comment]
@tjwebb I have the same issue affecting `attachDefaultRole` where it is using the default implementation and mixing users up in the promise chain due to the lack of bluebird's magic `bind()`.

**Comment by tjwebb** [comment]
cc @ryanwilliamquinn
