### ISSUE TITLE
Cannot find module sails-auth

### ISSUE THREAD

**Issue by ghadeerrahhal** [tjwebb/sails-permissions#91]
The latest version of sails-permissions results in the following error. To get around this, I reverted to version 1.2.2 which seems to works fine at the moment.

Error: Cannot find module 'sails-permissions/api/hooks/sails-auth'
    at Function.Module._resolveFilename (module.js:336:15)
    at Function.Module._load (module.js:278:25)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at Object.<anonymous> (/*/api/hooks/sails-auth.js:4:18)
    at Module._compile (module.js:460:26)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)

**Comment by michelbb** [comment]
I can confirm this problem.

**Comment by dottodot** [comment]
Yes same for me too.

**Comment by dbkaplun** [comment]
:+1:

**Comment by dottodot** [comment]
That commit hasn't made any different to the original issue reported.

**Comment by dottodot** [comment]
OK just found the reason. A previous version of sails-permissions must have installed files in api/hooks, and these need to be removed
